DEBUG: Rule 'rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "917a154c3890c1e8f21c070280926454637cd290162f4ee6174877ce3566cc8b"
DEBUG: Repository rules_python instantiated at:
  /Users/ajocard/Developments/logic/bm/numpy_test/WORKSPACE:8:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_ajocard/540f38b36a25b6b01d3f92498164cf3b/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /Users/ajocard/Developments/logic/bm/numpy_test/main/BUILD:6:10: no such package '@numpy_test_requirements//pypi__chardet': BUILD file not found in directory 'pypi__chardet' of external repository @numpy_test_requirements. Add a BUILD file to a directory to mark it as a package. and referenced by '//main:main'
ERROR: Analysis of target '//main:main' failed; build aborted: Analysis failed
INFO: Elapsed time: 14.545s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)